language: android
android:
  components:
  - platform-tools
  # KitKat https://source.android.com/source/build-numbers.html
  - build-tools-19
  - android-19 
  
sudo: false
cache:
  directories:
    - node_modules 
      
before_install:
# Setup npm and dep
#  - sudo apt-get install nodejs npm
  - npm install -g gulp
  - npm install --dev
  
before_script:
  - gulp cordova:init clean less
  
script: 
  - gulp cordova:build
