language: android
android:
  components:
  - platform-tools
  - build-tools
  - android-19
  - android-22
  - android-23
sudo: false
cache:
  directories:
  - node_modules
  - bower_components
before_install:
- openssl aes-256-cbc -k "$encrypted_key" -iv "$encrypted_iv" -in sofia-release-key.keystore.enc -out sofia-release-key.keystore -d
- nvm install 5.1 && nvm alias default 5.1 && nvm use 5.1
- npm install -g npm gulp cordova snyk
- snyk auth $SNYK_KEY
before_script:
- npm install
- snyk test || echo "Some librarie(s) need fix"
- sed -i '/android {/a lintOptions { abortOnError false } ' platforms/android/build.gradle
- gulp clean
- gulp
script:
- gulp cordova:build
- find ./www -type f -name '*.less' -delete
- find ./www -type f -name '*.map' -delete
- find ./www/assets -type f -name '*.js' -delete
- rm -Rf www/assets/js www/assets/less www/assets/platform/android/less www/assets/platform/browser
- cordova build android --release
- ls platforms/android/build/outputs/apk/
after_success:
- cd platforms/android/build/outputs/apk/
- cp android-armv7-release-unsigned.apk android-armv7-release-signed.apk
- cp android-x86-release-unsigned.apk android-x86-release-signed.apk
- jarsigner -verbose -sigalg SHA1withRSA -storepass "$STOREPASS" -keypass "$KEYPASS" -digestalg SHA1 -keystore sofia-release-key.keystore android-armv7-release-signed.apk sofia
- jarsigner -verbose -sigalg SHA1withRSA -storepass "$STOREPASS" -keypass "$KEYPASS" -digestalg SHA1 -keystore sofia-release-key.keystore android-x86-release-signed.apk sofia
- jarsigner -verify -verbose -certs android-armv7-release-signed.apk
- jarsigner -verify -verbose -certs android-x86-release-signed.apk
- md5sum *.apk
- sha512sum *.apk
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: REgeIaHbBjMektIqH+sdlmdqtz9KCn5wUcPtamMvquwFUn676VtBqTwYAPUsrq46FojKM1t3unXjSdp1rwslijX0Q9NTZW0FOnkbfmUB4PwveSTFcr1oBd0h+APfYnSiw62RHW6+JjGrK0jNQLQAA35PTows4FKW8mIyzzDWFT+LklHoQ4NP3NNp2hqXmMbcsVkQtEdHhN2a+Kh3zFEnCzDeoQN7BqhJmHIeKR23cK0I9P4wAyJjPkvcFtb32D93TyN3ysBS6l4LNeYI5aAGdf5KKJez66Hipo3L3A03BTsIfMxSlPrhmw3REWje9xFxDUCvyH4E7WxjMo1oICJQ+N6VEUTHSb0OMMByTxz+3gxf9slydR5d23Uy4c6XFGBB6DLwa97cRgs7wM/k0XgfK7lwQg+20fs4IoesGp+6TqpfR9M4IgYjX2XEg2A5bF62dKJjVWWeCAQtWqRlgStKNpUSI27s786mHRQZdlPf2rJ8uyd5zUbhjJ2wCRJX08nVff4TGKDJJvLjvu+/nni4NjGrft1sxgBQIe29zPlJ7CTh29qRLNTbis/Uodi76YaQQV352/R9sowRIkKFGH34grvXgtiKbTPuvkhcN4XfUu7Dm+QCoS5C5u0etHUIo3hqRhq0po1HmIqkT7c6QGERKVFbpT5OwynYjzHYKmmrECc=
  file: 
    - "android-armv7-release-unsigned.apk"
    - "android-x86-release-unsigned.apk"
    - "android-armv7-release-signed.apk"
    - "android-x86-release-signed.apk"
  on:
    tags: true
