language: android
android:
  components:
  - platform-tools
  - build-tools
  # KitKat https://source.android.com/source/build-numbers.html
  - android-19 
  # Par défaut dans cordova
  - android-22
  
sudo: false
cache:
  directories:
    - node_modules 
    - bower_components
      
before_install:
# Setup npm and dep
#  - sudo apt-get install nodejs npm
  - nvm install 5.1 && nvm alias default 5.1 && nvm use 5.1
  - npm install -g npm gulp cordova
  - npm install 
  
before_script:
# - gulp cordova:init clean less # Done in npm postinstall
 - gulp clean less
  
script: 
  - gulp cordova:build
  - cordova build android --release

after_success: 
  - cp platforms/android/build/outputs/apk/android-release-unsigned.apk platforms/android/build/outputs/apk/android-release-signed.apk
  - jarsigner -verbose -sigalg SHA1withRSA -storepass $STOREPASS -keypass $KEYPASS -digestalg SHA1 -keystore sophia-release-key.keystore platforms/android/build/outputs/apk/android-release-signed.apk SOPHIA 
  - zipalign -v 4 platforms/android/build/outputs/apk/android-release-signed.apk platforms/android/build/outputs/apk/android-release-signed-aligned.apk
  - md5sum platforms/android/build/outputs/apk/*.apk
  - sha512sum platforms/android/build/outputs/apk/*.apk
